version: "3"
services:
  mongodb:
    image: mongo:4.4
    container_name: "mongo"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:1.0
    build: .
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    depends_on:
        - mongodb
